### PR TITLE
Sync accent colors with ubuntu/yaru

### PR DESCRIPTION
**Pull request by jpnurmi**
https://github.com/ubuntu/yaru/blob/master/common/accent-colors.scss.in

See also:
- https://github.com/canonical/ubuntu-desktop-installer/issues/1560

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Looks like a mistake to me. So LGTM. However the new red will be problematic, but I guess we need to align this in general. Additional information is this comment of mine from discord:

there will be in yaru.dart places were I've lightened up the super weak saturated and dark accent colors like sage and bark because the contrast was extremely ... bad? weak? not good? (gonna be careful now) on the dark theme. I hope I have documented this correctly in the code   but this is unrelated to the plain missmatch in yaru_colors hex' code, which I have no explanation other than brain farts (Bearbeitet)
[17:24]
ah, here is the commit  

https://github.com/ubuntu/yaru.dart/pull/268

**Review by Feichtmeier — APPROVED** [review]

**Review by Jupi007 — APPROVED** [review]
Sorry for the late answer.

LGFM :+1:

**Comment by jpnurmi** [comment]
Thanks!

See also https://github.com/canonical/ubuntu-desktop-installer/issues/1560#issuecomment-1478070046

> However, it's worth mention that we do some math when it comes to use the accents in some cases...
> 
> For example we do have a `optimize-contrast($bg_color, $accent_bg_color);` (done via https://github.com/ubuntu/yaru/blob/master/common/sass-utils.scss#L201-L209) to compute the colors to be used in libadwaita apps when the accent is used as foreground value, but it's just happening in few cases.

We could probably sync our color tweaks with that algo?

**Comment by Feichtmeier** [comment]
> 

I used the built-in material mechanism to determine if a bg is dark or light and if it is dark the foreground color is light and vice versa
the use case for marcos tweaks are a tiny bit different

**Comment by jpnurmi** [comment]
Flutter's luminance computation is fine but I mean the algorithm to lighten or darken a color until a certain contrast level is achieved. :)

**Comment by Feichtmeier** [comment]
> Flutter's luminance computation is fine but I mean the algorithm to lighten or darken a color until a certain contrast level is achieved. :)

Sure, alternatively or additionally we could have elio and the guy who initially proposed the accent colors in 22.04 to rethink some of them
I find especially bark and sage to be very problematic accent colours in general. As they have very low saturation and look rather muddy making clear corners/edges especially with thin strokes really really hard to realize and you have to lighten them up for the dark theme until they have not much to do with the initial color

**Pull request merged**
