### PR TITLE
Release v0.1.7

### PR DESCRIPTION
**Pull request by jpnurmi**
* #29
* #28

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Sec, sorry. I prefer to test the colours before we merge this. Sorry for not holding back the other PR, bit :dizzy_face: yesterday

The current flutter accent colours were tested against the current surface and background colours. Objectively marking  a colour difference makes ofc total sense for people not involved in the process, however I need to make sure everything still works

**Comment by Feichtmeier** [comment]
Note: I find the place of the colours in this repository rather odd. Could we move back the colour definitions to yaru.dart please? The colour generation parts are ofc nice in here but this dependency is impractical, in my humble opinion

**Comment by jpnurmi** [comment]
> Note: I find the place of the colours in this repository rather odd. Could we move back the colour definitions to yaru.dart please? The colour generation parts are ofc nice in here but this dependency is impractical, in my humble opinion

I'd be fine with having all of this in yaru.dart if you're fine with having melos there because the builder and generator must be separate packages.

**Comment by Feichtmeier** [comment]
Would this mean that one needs to run melos after she changed the colours but not if she changed the theme parts? Or every time?

**Comment by jpnurmi** [comment]
The way melos is set up here makes it 100% optional. You don't ever _need_ to run melos.

All it does is help us execute flutter-aware tasks in multiple projects in one go.

- how to analyze multiple flutter projects
- how to run tests and collect coverage for multiple flutter projects
- how to format multiple flutter projects
- how to run build runner for multiple flutter projects
- how to run pub for multiple flutter projects
- how to update goldens in all relevant flutter projects

**Review by Feichtmeier — APPROVED** [review]
Tested locally and colours still work except red. However this should not hold back this release, should it?

**Comment by Feichtmeier** [comment]
> The way melos is set up here makes it 100% optional. You don't ever _need_ to run melos.
> 
> All it does is help us execute flutter-aware tasks in multiple projects in one go.
> 
>     * how to analyze multiple flutter projects
> 
>     * how to run tests and collect coverage for multiple flutter projects
> 
>     * how to format multiple flutter projects
> 
>     * how to run build runner for multiple flutter projects
> 
>     * how to run pub for multiple flutter projects
> 
>     * how to update goldens in all relevant flutter projects

I am not sure about this one yet.
Couldn't we move the static colours to yaru.dart without melos but keep everything dynamic with builder/generator things in here?

**Comment by jpnurmi** [comment]
> I am not sure about this one yet. Couldn't we move the static colours to yaru.dart without melos but keep everything dynamic with builder/generator things in here?

Could you help me to understand the problem? It's no different from having shell scripts for executing tasks except that melos is Flutter-aware and even comes with a vscode extension.

**Comment by Feichtmeier** [comment]
I personally prefer to keep everything as simple as possible. Without melos you can open a flutter project with vscode and press the run button and it runs. Because everything is inside this one package.
Can't we move the static color definitions into yaru.dart? And keep the rest here. This will become very interesting when gnome supports custom accent colors.

**Comment by jpnurmi** [comment]
[Screencast from 2023-03-22 16-39-51.webm](https://user-images.githubusercontent.com/140617/226958366-e8bc1b3d-01fd-4279-8be5-a55a8479d145.webm)

**Comment by jpnurmi** [comment]
In the previous video, I intentionally did not press "pub get" as automatically proposed by VS Code just to show that "open and press run" just works. That one button press to run "pub get" gets rid of all the red visible in the previous video.

[Screencast from 2023-03-22 16-41-49.webm](https://user-images.githubusercontent.com/140617/226959265-22bd4893-d2fd-4332-82e3-5d3d61a9325b.webm)

**Comment by Feichtmeier** [comment]
btw you can merge the PR

fine, then the run problem is a no problem
However you elegantly dodge my question twice 😆 

> Can't we move the static color definitions into yaru.dart? And keep the rest here.

**Comment by jpnurmi** [comment]
Moving the constants would introduce a wrong-way dependency and make it difficult to work with the remaining projects here. While you are focusing on moving a few constants, I'm looking at the whole infrastructure that we've already built here.

**Comment by Feichtmeier** [comment]
My second point was that it is impractical to need to open yaru colors, make a change, make a release, if you want to improve any colour constant. I think we agree there?
Sorry if I missed this in your explanation(s) but why do we need melos for 10+ color constants in yaru.dart? (that were originally there, which is no argument though)

**Comment by Feichtmeier** [comment]
To explain what I think we should do:

- yaru.dart should not have any yaru_colors in pubspec *at all*
- yaru_colors.dart could keep those two packages to generate colors that are *not* the 8? default primary material colors and not the X shades of grey/white

**Comment by jpnurmi** [comment]
> My second point was that it is impractical to need to open yaru colors, make a change, make a release, if you want to improve any colour constant. I think we agree there?

Yes, and we could've had all this in yaru.dart if it wasn't for melos that drove us here into a separate repo. Now that we've spent all the energy and effort building the infrastructure here, it's not just a matter of moving a few lines of code around.

> Sorry if I missed this in your explanation(s) but why do we need melos for 10+ color constants in yaru.dart? (that were originally there, which is no argument though)

There's a technical reason for dividing things into separate packages. `yaru_color_builder` is a dev-dependency to avoid introducing build-time tooling as a run-time dependency for all Yaru apps. :)

**Comment by Feichtmeier** [comment]
ooook then I need to open the repo locally and show you what I mean 😢

**Comment by Feichtmeier** [comment]
new file "colors.dart"

```dart
import 'package:flutter/material.dart';

const Color coolGrey = Color(0xFF333333);
const Color textGrey = Color(0xFF111111);
const Color error = Color(0xFFff0000);
const Color warning = Color(0xFFf99b11);
const Color success = Color(0xFF0e8420);
const Color porcelain = Color(0xFFFAFAFA);
const Color inkstone = Color(0xFF3B3B3B);
const Color jet = Color(0xFF2B2B2B);
const Color titleBarLight = Color(0xFFEBEBEB);

const Color titleBarDark = Color(0xFF303030);
const MaterialColor orange = MaterialColor(0xFFE95420, {
  50: Color(0xFFF9E9E7),
  100: Color(0xFFFBCCBC),
  200: Color(0xFFF9AB91),
  300: Color(0xFFF68A65),
  400: Color(0xFFF57144),
  500: Color(0xFFF45A24),
  600: Color(0xFFE95420),
  700: Color(0xFFDB4D1B),
  800: Color(0xFFCD4718),
  900: Color(0xFFB43B11)
});

const MaterialColor warmGrey = MaterialColor(0xFFAEA79F, {
  50: Color(0xFFFFFAF2),
  100: Color(0xFFFDF5ED),
  200: Color(0xFFF8F1E8),
  300: Color(0xFFEFE7DF),
  400: Color(0xFFCCC5BD),
  500: Color(0xFFAEA79F),
  600: Color(0xFF847D76),
  700: Color(0xFF6F6961),
  800: Color(0xFF4F4942),
  900: Color(0xFF2D2821)
});

const MaterialColor olive = MaterialColor(0xFF4B8501, {
  50: Color(0xFFF1F7E6),
  100: Color(0xFFDBEAC0),
  200: Color(0xFFC3DD97),
  300: Color(0xFFAACF6C),
  400: Color(0xFF97C54A),
  500: Color(0xFF84BC22),
  600: Color(0xFF75AC1A),
  700: Color(0xFF60990E),
  800: Color(0xFF4B8501),
  900: Color(0xFF226400)
});

const MaterialColor bark = MaterialColor(0xFF787859, {
  50: Color(0xFFFDFCD9),
  100: Color(0xFFF8F7D4),
  200: Color(0xFFF2F1CE),
  300: Color(0xFFE4E3C0),
  400: Color(0xFFC1C09E),
  500: Color(0xFFA2A181),
  600: Color(0xFF787859),
  700: Color(0xFF646446),
  800: Color(0xFF444528),
  900: Color(0xFF232305)
});

const MaterialColor sage = MaterialColor(0xFF657B69, {
  50: Color(0xFFE8FFEC),
  100: Color(0xFFE3FCE7),
  200: Color(0xFFDCF5E0),
  300: Color(0xFFCEE7D2),
  400: Color(0xFFACC4B0),
  500: Color(0xFF8DA491),
  600: Color(0xFF657B69),
  700: Color(0xFF516755),
  800: Color(0xFF334737),
  900: Color(0xFF132617)
});

const MaterialColor prussianGreen = MaterialColor(0xFF308280, {
  50: Color(0xFFE1F7F6),
  100: Color(0xFFB6EBE8),
  200: Color(0xFF89DEDB),
  300: Color(0xFF60D0CE),
  400: Color(0xFF49C6C6),
  500: Color(0xFF3BBCC0),
  600: Color(0xFF38ACAE),
  700: Color(0xFF349696),
  800: Color(0xFF308280),
  900: Color(0xFF285E58)
});

const MaterialColor viridian = MaterialColor(0xFF03875B, {
  50: Color(0xFFE6F7EF),
  100: Color(0xFFC3EAD8),
  200: Color(0xFF9BDDC0),
  300: Color(0xFF70D0A7),
  400: Color(0xFF4BC694),
  500: Color(0xFF15BB81),
  600: Color(0xFF0DAB76),
  700: Color(0xFF049968),
  800: Color(0xFF03875B),
  900: Color(0xFF046744)
});

const MaterialColor purple = MaterialColor(0xFF7764D8, {
  50: Color(0xFFEDE9F9),
  100: Color(0xFFD0C9F1),
  200: Color(0xFFB1A5E8),
  300: Color(0xFF9180DF),
  400: Color(0xFF7764D8),
  500: Color(0xFF5C4AD0),
  600: Color(0xFF5145CA),
  700: Color(0xFF403DC0),
  800: Color(0xFF3037B8),
  900: Color(0xFF092CAA)
});

const MaterialColor red = MaterialColor(0xFFDA3450, {
  50: Color(0xFFFBE4E9),
  100: Color(0xFFF6BBC8),
  200: Color(0xFFEF90A4),
  300: Color(0xFFE86581),
  400: Color(0xFFE14967),
  500: Color(0xFFDA3450),
  600: Color(0xFFCA2F4E),
  700: Color(0xFFB52A4A),
  800: Color(0xFFA12547),
  900: Color(0xFF7D1D40)
});

const MaterialColor blue = MaterialColor(0xFF0073E5, {
  50: Color(0xFFE2F2FF),
  100: Color(0xFFBADEFF),
  200: Color(0xFF8CCAFF),
  300: Color(0xFF59B4FF),
  400: Color(0xFF2CA4FF),
  500: Color(0xFF0094FF),
  600: Color(0xFF0086F9),
  700: Color(0xFF0073E5),
  800: Color(0xFF0861D3),
  900: Color(0xFF0F41B4)
});

const MaterialColor magenta = MaterialColor(0xFFB34CB3, {
  50: Color(0xFFF4E6F4),
  100: Color(0xFFE4C0E4),
  200: Color(0xFFD396D3),
  300: Color(0xFFC16CC1),
  400: Color(0xFFB34CB3),
  500: Color(0xFFA52FA6),
  600: Color(0xFF972BA0),
  700: Color(0xFF852598),
  800: Color(0xFF752090),
  900: Color(0xFF591782)
});

const MaterialColor kubuntuBlue = MaterialColor(0xFF0079C1, {
  50: Color(0xFFE1F5FF),
  100: Color(0xFFB3E6FD),
  200: Color(0xFF81D5FC),
  300: Color(0xFF4FC5FA),
  400: Color(0xFF27B8FA),
  500: Color(0xFF00ABF8),
  600: Color(0xFF009DE9),
  700: Color(0xFF008AD5),
  800: Color(0xFF0079C1),
  900: Color(0xFF00599F)
});

const MaterialColor lubuntuBlue = MaterialColor(0xFF0068C8, {
  50: Color(0xFFE3F3FE),
  100: Color(0xFFBBDFFD),
  200: Color(0xFF8FCCFD),
  300: Color(0xFF60B8FC),
  400: Color(0xFF3AA8FC),
  500: Color(0xFF069AFB),
  600: Color(0xFF068BED),
  700: Color(0xFF0279DA),
  800: Color(0xFF0068C8),
  900: Color(0xFF004AA9)
});

const MaterialColor ubuntuBudgieBlue = MaterialColor(0xFF2196F3, {
  50: Color(0xFFE3F2FD),
  100: Color(0xFFBBDEFB),
  200: Color(0xFF90CAF9),
  300: Color(0xFF64B5F6),
  400: Color(0xFF42A5F5),
  500: Color(0xFF2196F3),
  600: Color(0xFF1E88E5),
  700: Color(0xFF1976D2),
  800: Color(0xFF1565C0),
  900: Color(0xFF0D47A1)
});

const MaterialColor ubuntuButterflyPink = MaterialColor(0xFFFF135B, {
  50: Color(0xFFFFE5EB),
  100: Color(0xFFFFBCCE),
  200: Color(0xFFFF90AE),
  300: Color(0xFFFF628D),
  400: Color(0xFFFF3D74),
  500: Color(0xFFFF135B),
  600: Color(0xFFEE0B59),
  700: Color(0xFFD80256),
  800: Color(0xFFC40053),
  900: Color(0xFFA0004F)
});

const MaterialColor ubuntuCinnamonBrown = MaterialColor(0xFFDD682A, {
  50: Color(0xFFFEF4E4),
  100: Color(0xFFFDE4BB),
  200: Color(0xFFFDD290),
  300: Color(0xFFFCC065),
  400: Color(0xFFFCB349),
  500: Color(0xFFFBA63A),
  600: Color(0xFFF69B36),
  700: Color(0xFFF08C32),
  800: Color(0xFFE87E2E),
  900: Color(0xFFDD682A)
});

const MaterialColor ubuntuMateGreen = MaterialColor(0xFF73AF59, {
  50: Color(0xFFEFF8EB),
  100: Color(0xFFD8ECCE),
  200: Color(0xFFBEDFAE),
  300: Color(0xFFA5D28F),
  400: Color(0xFF92C978),
  500: Color(0xFF81BF62),
  600: Color(0xFF73AF59),
  700: Color(0xFF619B4E),
  800: Color(0xFF518745),
  900: Color(0xFF356433)
});

const MaterialColor ubuntuStudioBlue = MaterialColor(0xFF009BF9, {
  50: Color(0xFFE3F3FE),
  100: Color(0xFFBBE0FC),
  200: Color(0xFF8FCDFC),
  300: Color(0xFF61B9FA),
  400: Color(0xFF3AA9FA),
  500: Color(0xFF009BF9),
  600: Color(0xFF008DEB),
  700: Color(0xFF007BD8),
  800: Color(0xFF006AC6),
  900: Color(0xFF004BA8)
});

const MaterialColor ubuntuUnityPurple = MaterialColor(0xFF9005D5, {
  50: Color(0xFFF4E5FA),
  100: Color(0xFFE3BEF4),
  200: Color(0xFFD291EE),
  300: Color(0xFFBF63E7),
  400: Color(0xFFB03CE2),
  500: Color(0xFFA100DB),
  600: Color(0xFF9005D5),
  700: Color(0xFF7807CE),
  800: Color(0xFF6107C8),
  900: Color(0xFF2308C0)
});

const MaterialColor xubuntuBlue = MaterialColor(0xFF0044AA, {
  50: Color(0xFFE2F2FE),
  100: Color(0xFFBADEFE),
  200: Color(0xFF8CC9FE),
  300: Color(0xFF5CB4FD),
  400: Color(0xFF33A4FE),
  500: Color(0xFF0094FD),
  600: Color(0xFF0086EE),
  700: Color(0xFF0074DB),
  800: Color(0xFF0063C9),
  900: Color(0xFF0044AA)
});
```

```diff
diff --git a/lib/src/themes/common_themes.dart b/lib/src/themes/common_themes.dart
index 51a7799..0ebe81c 100644
--- a/lib/src/themes/common_themes.dart
+++ b/lib/src/themes/common_themes.dart
@@ -1,9 +1,9 @@
 import 'package:flutter/material.dart';
 import 'package:flutter/services.dart';
+import 'package:yaru/src/colors.dart';
 import 'package:yaru/src/text/text_theme.dart';
 import 'package:yaru/src/themes/constants.dart';
 import 'package:yaru/src/themes/page_transitions.dart';
-import 'package:yaru_colors/yaru_colors.dart';
 
 const kDividerColorDark = Color.fromARGB(255, 65, 65, 65);
 const kDividerColorLight = Color(0xffdcdcdc);
@@ -203,9 +203,7 @@ ToggleButtonsThemeData _createToggleButtonsTheme(ColorScheme colorScheme) {
 // Dialogs
 
 DialogTheme _createDialogTheme(ColorScheme colorScheme) {
-  final bgColor = colorScheme.brightness == Brightness.dark
-      ? YaruColors.jet
-      : YaruColors.porcelain;
+  final bgColor = colorScheme.brightness == Brightness.dark ? jet : porcelain;
   return DialogTheme(
     backgroundColor: bgColor,
     surfaceTintColor: bgColor,
@@ -283,7 +281,7 @@ Color _getCheckColor(Set<MaterialState> states, ColorScheme colorScheme) {
         ? Colors.black
         : Colors.white;
   }
-  return YaruColors.warmGrey;
+  return warmGrey;
 }
 
 CheckboxThemeData _getCheckBoxThemeData(ColorScheme colorScheme) {
@@ -443,31 +441,31 @@ ThemeData createYaruLightTheme({
 }) {
   final colorScheme = ColorScheme.fromSeed(
     seedColor: primaryColor,
-    error: YaruColors.error,
+    error: error,
     brightness: Brightness.light,
     primary: primaryColor,
     onPrimary: contrastColor(primaryColor),
-    primaryContainer: YaruColors.porcelain,
-    onPrimaryContainer: YaruColors.inkstone,
-    inversePrimary: YaruColors.inkstone,
+    primaryContainer: porcelain,
+    onPrimaryContainer: inkstone,
+    inversePrimary: inkstone,
     secondary: elevatedButtonColor ?? primaryColor,
     onSecondary: contrastColor(elevatedButtonColor ?? primaryColor),
     secondaryContainer:
         elevatedButtonColor?.withOpacity(0.4) ?? primaryColor.withOpacity(0.4),
-    onSecondaryContainer: elevatedButtonTextColor ?? YaruColors.jet,
```

**Comment by jpnurmi** [comment]
I feel like I've seen this somewhere before :D

https://github.com/ubuntu/yaru.dart/blob/cfc4e688dadc2ab43f8f47d9b2c89a737a8a23ee/lib/src/colors/yaru_colors.dart

**Comment by Feichtmeier** [comment]
yes, it might be bad for the 3 moments in 10 years where one needs to change the palette but then yaru_colors.dart is handy and there could be even some dart output here

grafik

then the basic colours are all statically in yaru.dart and the generation stays here

it is just an idea. if you don't like it we dont have to

**Comment by jpnurmi** [comment]
The "static" colors are generated, too. The algorithm is in `yaru_color_generator`. `yaru_colors` uses it for run-time generation and `yaru_color_builder` for build-time generation. If you want to merge `yaru_colors` into `yaru` then it makes the most sense to move it together with the other lego blocks that it logically belongs together with to avoid circular dependencies.

The old way of doing it all by hand was definitely easier to understand but it came with a cost of things getting randomly out of sync. Well, somehow we managed to get out of sync even with a system of generated colors where we only need to feed in one value.

**Comment by Feichtmeier** [comment]
> The "static" colors are generated, too. 

yes yes I understand this ;)

> circular dependencies

there would not be any dep from yaru_colors->yaru if we would have this colours file with the default colours
If we would do this we would then remove those colours from yaru_colors and only keep the generation part in here. No YaruColors classes in yaru. All const. 

Workflow wise it would be a lot easier especially soon when we want to iterate over contrast improvements.

**Comment by Feichtmeier** [comment]
One of the reasons I rarely try to improve the contrast situation is because it is incredibly painful to 

- change yaru_colors
- use this branch in yaru
- see if it fits
- repeat

if there would just be this one single file in yaru.dart it would be super easy

and concerning those shades of material colors. We actually do not need them anymore. Since flutter changed this from seed thing you only need the one Color(0x....)

**Comment by jpnurmi** [comment]
> and concerning those shades of material colors. We actually do not need them anymore. Since flutter changed this from seed thing you only need the one Color(0x....)

Bingo! That's a good enough reason to deprecate all of yaru_colors.dart! :+1: 

The whole reason I invented yaru_colors.dart was that I was supposed to update some of the broken shades but nobody seemed to have an explanation for where they even came from. :D If we don't need the shades, we don't need yaru_colors.dart at all! :tada:

R.I.P. yaru_colors

**Comment by Feichtmeier** [comment]
lol, are you being sarcastic? : D

**Comment by jpnurmi** [comment]
No, I'm actually not! :) I mean it, this whole repo is based on the obsolete M2 color tool algorithm: https://observablehq.com/@mateh/palette. We don't need the shades, we don't need any of these packages. As simple as that! :D

**Comment by jpnurmi** [comment]
+1 for bringing the accent colors into yaru.dart as single-color constants without any generated shades. We should somehow find a way to keep them in sync with https://github.com/ubuntu/yaru/blob/master/common/accent-colors.scss.in. I recall Paul introduced some helpful color extensions here that we might want to move also.

**Comment by Feichtmeier** [comment]
Okay! If we need colour generation again in the future we could come back to yaru_colors? I did not want to belittle the work you have done here in any way

**Comment by jpnurmi** [comment]
I recall the Material team introduced something for M3 palettes that might be better choices if we need something in the future. Could be one of these packages:
- https://pub.dev/packages/material_color_utilities
- https://pub.dev/packages/dynamic_color

**Comment by jpnurmi** [comment]
I have a small wish. :) Can we keep the API the same so that we can simply drop the `yaru_colors` dependency when upgrading to `yaru: ^0.7.0`?

Before, in yaru_colors:
```dart
class YaruColors {
  static const MaterialColor foo;
}
```

After, in yaru:
```dart
class YaruColors {
  static const Color foo;
}
```

**Comment by Feichtmeier** [comment]
nice idea! don't need to be constsstss, classes are fine

**Pull request merged**
