### PR TITLE
Release yaru_colors version 0.1.3

### PR DESCRIPTION
**Pull request by Jupi007**

### CODE REVIEW

**Review by jpnurmi — APPROVED** [review]
Thanks, LGTM :+1:

**Comment by Jupi007** [comment]
The tests looks not be able to run correctly, but I think I still can merge?

**Comment by Jupi007** [comment]
@jpnurmi I don't have admin access on this repo, and I can't force merge this PR because of the failed checks. Can you do it, please?

**Comment by jpnurmi** [comment]
Good to go! :+1:

**Comment by Jupi007** [comment]
Thanks :)

**Pull request merged**
